// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: UI

#ifndef _UI_UI_COMP_HOOK_H
#define _UI_UI_COMP_HOOK_H

#ifdef __cplusplus
extern "C" {
#endif

void ui_comp_Alarm_Comp_create_hook(lv_obj_t * comp);
void ui_comp_Clock_Dot_create_hook(lv_obj_t * comp);
void ui_comp_Scrolldots_create_hook(lv_obj_t * comp);
void ui_comp_Small_Label_create_hook(lv_obj_t * comp);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
