// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: UI

#include "../ui.h"

void ui_Splash_screen_init(void)
{
    ui_Splash = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Splash, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Splash, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Splash, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Demo = ui_Small_Label_create(ui_Splash);
    lv_obj_set_x(ui_Demo, 0);
    lv_obj_set_y(ui_Demo, 75);
    lv_obj_set_align(ui_Demo, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Demo, "by digiexchris");
    lv_obj_set_style_text_color(ui_Demo, lv_color_hex(0x9C9CD9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Demo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MeltingFurnace = ui_Small_Label_create(ui_Splash);
    lv_obj_set_x(ui_MeltingFurnace, 0);
    lv_obj_set_y(ui_MeltingFurnace, 50);
    lv_obj_set_align(ui_MeltingFurnace, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MeltingFurnace, "Melting_Furnace");
    lv_obj_set_style_text_color(ui_MeltingFurnace, lv_color_hex(0x000746), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MeltingFurnace, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Logo = lv_image_create(ui_Splash);
    lv_image_set_src(ui_Logo, &ui_img_smelting_png);
    lv_obj_set_width(ui_Logo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Logo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Logo, 0);
    lv_obj_set_y(ui_Logo, -49);
    lv_obj_set_align(ui_Logo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Logo, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_Logo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_Logo, 80);

    lv_obj_add_event_cb(ui_Splash, ui_event_Splash, LV_EVENT_ALL, NULL);
    uic_Melting_Furnace = ui_MeltingFurnace;

}
