// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: UI

#include "../ui.h"

void ui_Temp_screen_init(void)
{
    ui_Temp = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Temp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_Temp, &ui_img_pattern_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_tiled(ui_Temp, true, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Arc1 = lv_arc_create(ui_Temp);
    lv_obj_set_width(ui_Arc1, lv_pct(80));
    lv_obj_set_height(ui_Arc1, lv_pct(60));
    lv_obj_set_x(ui_Arc1, -2);
    lv_obj_set_y(ui_Arc1, -41);
    lv_obj_set_align(ui_Arc1, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_Arc1, 0, 1350);
    lv_arc_set_value(ui_Arc1, 50);

    ui_CurrentTemp = lv_label_create(ui_Temp);
    lv_obj_set_width(ui_CurrentTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CurrentTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CurrentTemp, -2);
    lv_obj_set_y(ui_CurrentTemp, -66);
    lv_obj_set_align(ui_CurrentTemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CurrentTemp, "9999C");
    lv_obj_set_style_text_font(ui_CurrentTemp, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SetTemp = lv_label_create(ui_Temp);
    lv_obj_set_width(ui_SetTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SetTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SetTemp, -2);
    lv_obj_set_y(ui_SetTemp, -16);
    lv_obj_set_align(ui_SetTemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SetTemp, "1150C");
    lv_obj_set_style_text_font(ui_SetTemp, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LowerLimit = lv_label_create(ui_Temp);
    lv_obj_set_width(ui_LowerLimit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LowerLimit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LowerLimit, -62);
    lv_obj_set_y(ui_LowerLimit, 48);
    lv_obj_set_align(ui_LowerLimit, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LowerLimit, "0C");
    lv_obj_set_style_text_font(ui_LowerLimit, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_UpperLimit = lv_label_create(ui_Temp);
    lv_obj_set_width(ui_UpperLimit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_UpperLimit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_UpperLimit, 53);
    lv_obj_set_y(ui_UpperLimit, 48);
    lv_obj_set_align(ui_UpperLimit, LV_ALIGN_CENTER);
    lv_label_set_text(ui_UpperLimit, "1350C");
    lv_obj_set_style_text_font(ui_UpperLimit, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OnOff = lv_button_create(ui_Temp);
    lv_obj_set_width(ui_OnOff, 180);
    lv_obj_set_height(ui_OnOff, 64);
    lv_obj_set_x(ui_OnOff, -2);
    lv_obj_set_y(ui_OnOff, 110);
    lv_obj_set_align(ui_OnOff, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_OnOff, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_OnOff, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_OnOff, lv_color_hex(0x00BC4A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_OnOff, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OnOffButtonLabel = lv_label_create(ui_OnOff);
    lv_obj_set_width(ui_OnOffButtonLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_OnOffButtonLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_OnOffButtonLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_OnOffButtonLabel, " Start");
    lv_obj_set_style_text_font(ui_OnOffButtonLabel, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Arc1, ui_event_Arc1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_OnOff, ui_event_OnOff, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Temp, ui_event_Temp, LV_EVENT_ALL, NULL);
    uic_OnOffButtonLabel = ui_OnOffButtonLabel;

}
