// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: UI

#ifndef _UI_UI_H
#define _UI_UI_H

#ifdef __cplusplus
extern "C"
{
#endif

#include "lvgl.h"

#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"
#include "ui_helpers.h"

	void upanim_Animation(lv_obj_t *TargetObject, int delay);
	void hour_Animation(lv_obj_t *TargetObject, int delay);
	void min_Animation(lv_obj_t *TargetObject, int delay);
	void sec_Animation(lv_obj_t *TargetObject, int delay);
	void scrolldot_Animation(lv_obj_t *TargetObject, int delay);

	// SCREEN: ui_Splash
	void ui_Splash_screen_init(void);
	void ui_event_Splash(lv_event_t *e);
	extern lv_obj_t *ui_Splash;
	extern lv_obj_t *ui_Demo;
	extern lv_obj_t *ui_MeltingFurnace;
	extern lv_obj_t *ui_Logo;
	// CUSTOM VARIABLES
	extern lv_obj_t *uic_Melting_Furnace;

	// SCREEN: ui_Temp
	void ui_Temp_screen_init(void);
	void ui_event_Temp(lv_event_t *e);
	extern lv_obj_t *ui_Temp;
	void ui_event_Arc1(lv_event_t *e);
	extern lv_obj_t *ui_Arc1;
	extern lv_obj_t *ui_CurrentTemp;
	extern lv_obj_t *ui_SetTemp;
	extern lv_obj_t *ui_LowerLimit;
	extern lv_obj_t *ui_UpperLimit;
	void ui_event_OnOff(lv_event_t *e);
	extern lv_obj_t *ui_OnOff;
	extern lv_obj_t *ui_OnOffButtonLabel;
	// CUSTOM VARIABLES
	extern lv_obj_t *uic_OnOffButtonLabel;

	// SCREEN: ui_Settings
	void ui_Settings_screen_init(void);
	void ui_event_Settings(lv_event_t *e);
	extern lv_obj_t *ui_Settings;
	// CUSTOM VARIABLES

	// EVENTS
	extern lv_obj_t *ui____initial_actions0;

	// IMAGES AND IMAGE SETS
	LV_IMG_DECLARE(ui_img_smelting_png); // assets/smelting.png
	LV_IMG_DECLARE(ui_img_pattern_png);	 // assets/pattern.png

	// FONTS
	LV_FONT_DECLARE(ui_font_Number);

	// UI INIT
	void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
